plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.liucai.permission'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                artifact("$buildDir/outputs/aar/${project.name}-release.aar")
                groupId = 'com.github.liucai-bit'
                artifactId = 'lcaipermission' // 这里是你依赖时的名字
                version = '' // 这里建议留空，让 JitPack 通过 Tag 自动注入版本
            }
        }
    }

    // 确保发布任务在打包任务之后执行
    tasks.named('publishReleasePublicationToMavenLocal') {
        mustRunAfter tasks.named('bundleReleaseAar')
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}